<?php
/**
 * @file
 * File description
 *
 * Long description
 */

/**
 * Implements hook_help().
 */
function stanford_drupalcamp_features_help($path, $arg) {
  switch ($path) {
    // Main module help for the block module
    /*
     *case 'admin/help#block':
     *  return '<p>' . t('Blocks are boxes of content rendered into an area, or region, of a web page. The default theme Bartik, for example, implements the regions "Sidebar first", "Sidebar second", "Featured", "Content", "Header", "Footer", etc., and a block may appear in any one of these areas. The <a href="@blocks">blocks administration page</a> provides a drag-and-drop interface for assigning a block to a region, and for controlling the order of blocks within regions.', array('@blocks' => url('admin/structure/block'))) . '</p>';
     */
    case 'admin/help#stanford_drupalcamp_features':
      return '<p>' . t('There is no help for you. Why? Because, camp motto.') . '</p>';
  }
}


